version: "3.9"
services:
  deloitte-api:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        MODE: development
    environment:
      DB_HOST: "database"
      DB_USERNAME: "root"
      DB_PASSWORD: ""
      SECRET_KEY: "!#dn=z-wh@)gw91+^*=uef_&oj5+cq$id(-lh^1y1=8k-pw+0g"
    container_name: deloitte-api
    depends_on:
      - database
    volumes:
      - ./:/code
    ports:
      - "9999:9999"
    stdin_open: true
    tty: true

  database:
    platform: linux/x86_64
    image: percona
    volumes:
      - ./mysql_backup:/var/lib/mysql
    container_name: database
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
